FROM langchain/langgraph-api:0.11.1-py3.11

ARG VCS_REF="unknown"
ARG BUILD_DATE="unknown"
LABEL org.opencontainers.image.title="deep-research-agent" \
      org.opencontainers.image.description="LangGraph electronic literature research agent" \
      org.opencontainers.image.source="https://github.com/lyx001124/deep_research" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.created="${BUILD_DATE}"

# This installation sequence follows the Dockerfile generated by LangGraph CLI.
COPY . /deps/deep_research
RUN cd /deps/deep_research && \
    PYTHONDONTWRITEBYTECODE=1 uv pip install \
      --system --no-cache-dir -c /api/constraints.txt -e .

ENV LANGGRAPH_AUTH='{"path":"/deps/deep_research/src/security/auth.py:auth"}' \
    LANGSERVE_GRAPHS='{"Deep Researcher":"/deps/deep_research/src/open_deep_research/deep_researcher.py:deep_researcher"}' \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Restore the API package if a project dependency replaced its namespace.
RUN mkdir -p /api/langgraph_api /api/langgraph_runtime /api/langgraph_license && \
    touch /api/langgraph_api/__init__.py \
          /api/langgraph_runtime/__init__.py \
          /api/langgraph_license/__init__.py && \
    uv pip install --system --no-cache-dir --no-deps -e /api && \
    pip uninstall -y pip setuptools wheel && \
    rm -rf /usr/local/lib/python*/site-packages/pip* \
           /usr/local/lib/python*/site-packages/setuptools* \
           /usr/local/lib/python*/site-packages/wheel* && \
    find /usr/local/bin -name "pip*" -delete && \
    uv pip uninstall --system pip setuptools wheel && \
    rm -f /usr/bin/uv /usr/bin/uvx

WORKDIR /deps/deep_research
